### ISSUE TITLE
Highlight expiration condition blocks in TODO comments

### ISSUE THREAD

**Issue by zardoy** [jgclark/vscode-todo-highlight#24]
[Expiration blocks](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/expiring-todo-comments.md) seem to be very convenient thing to use. What do you think about highlighting them?

```ts
// TODO (@lubien) [>0]: Refactor for stable.
```

**Comment by jgclark** [comment]
The reason I took on maintaining this extension is to deliver regular expressions into its capability. Now it is that, you can define whatever use cases you want, using them.

See the README for examples on how to include them in your VSCode configuration. You might like to share the result here, so that I can include it as standard in future releases.
